language: node_js
node_js:
- '14'
# before_install:
# - npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
before_deploy:
  - if [ "$TRAVIS_BRANCH" == "master" ];then
    git checkout master;
    fi;
deploy:
  provider: heroku
  app: netflix-jul-zas
  api_key:
    secure: d8g5c0/HqhZlM47EvB3FI/UBYnBOHLu/eMSZ9Ez6+pW4WzbrcBaYKfm3PJeIq20B1c3ls10hHoQ7J9she1sWSOHFgw7xVB505YCfBuDHGLcJgqhqkpZh4t3XLdK29Xmbuik3acrnu70Z79TwUQu/Ix4oLxMYn5zsizPYR1ASOCcEjb97VJ7ulmy2EhF0KeEwxZHt39H9bF8Nqykhifs2lWbkCVxXDbnHgq4x7MT6UuD5XaOZSK1RR/t0dhFedieKlY5qHOE6ltiZGtfIKw/CVsezTHeBbR0jFbezSTpgZtjo6hfsl1lY/PNpZr8GbXhC4ouosEIEtVnHto2sPE6V8e7SH/T4hAbKblTfTzBI8QsthyBEcQpsg9mTGNT/CJ0pzrA8YPE7dhRh1SRSv4FYnTXBd3I1+BRTjLmCnS6yxRbE66nxGnqif90537baf1XE5TBGe47irXCPyM4XOYs02KBKKjdHtDcj+SZtSBmda0J02So3rUzDj9BNfOPw/PZQSPmWtpf+1EC5YbBHZ7wTVREOTnyhmvPkgkCfXJLL8QLMCUWrO6burKfuU6ApyLhQUs/TUst5p9fWLe/x+bArLjezoZrSv0CjOmbcr/aJDgVlZ9u46kMRlT1flf1XKuV3Zy2u8aNhf0wzjlvKsAPuLkl9DyxSMMgp1YhoIbv/rX0=
